;this file for FamiTone2 libary generated by nsf2data tool

sounds:
	.word @ntsc
	.word @pal
@ntsc:
	.word @sfx_ntsc_0
@pal:
	.word @sfx_pal_0

@sfx_ntsc_0:
	.byte $89,$37,$8a,$0f,$01,$8a,$06,$01,$8a,$0a,$01,$89,$31,$8a,$0f,$01
	.byte $89,$37,$8a,$04,$01,$8a,$08,$01,$89,$33,$02,$89,$31,$01,$00
@sfx_pal_0:
	.byte $89,$37,$8a,$0f,$01,$8a,$06,$01,$8a,$0a,$01,$89,$31,$8a,$0f,$01
	.byte $89,$37,$8a,$04,$01,$8a,$08,$01,$89,$33,$02,$89,$31,$01,$00
