# CMake toolchain file for cc65

set (CMAKE_SYSTEM_NAME Generic)
set (CMAKE_SYSTEM_PROCESSOR 6502)

set (CMAKE_C_COMPILER cc65)
set (CMAKE_C_COMPILER_ID cc65)
set (CMAKE_C_COMPILER_VERSION "2.18")

set (CMAKE_ASM_COMPILER ca65)
set (CMAKE_LINKER ld65)

# Test building with cc65 isn't going to work because labels aren't defined in the test program. Disable it.
set (CMAKE_C_COMPILER_WORKS TRUE)

set (CMAKE_DEPFILE_FLAGS_C "--create-dep <DEPFILE>")
set (CMAKE_C_VERBOSE_FLAG "-v")
set (CMAKE_C_FLAGS_DEBUG_INIT "-g -D DEBUG --asm-define DEBUG")

set (CMAKE_ASM_SOURCE_FILE_EXTENSIONS s;S;asm)

set (CMAKE_ASM_COMPILE_OBJECT "<CMAKE_ASM_COMPILER> <DEFINES> <INCLUDES> -o <OBJECT> <SOURCE>")
set (CMAKE_C_COMPILE_OBJECT "<CMAKE_C_COMPILER> <DEFINES> <INCLUDES> <FLAGS> -o <OBJECT>.s <SOURCE> && <CMAKE_ASM_COMPILER> <DEFINES> <INCLUDES> -o <OBJECT> <OBJECT>.s")

set (CMAKE_C_LINK_EXECUTABLE "<CMAKE_LINKER> <OBJECTS> <FLAGS> <CMAKE_C_LINK_FLAGS> <LINK_FLAGS> -o <TARGET> <LINK_LIBRARIES>")
